apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-incident-deployment
  namespace: ai-incident-namespace
  labels:
    app: ai-incident-manager

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ai-incident-manager

  template:
    metadata:
      labels:
        app: ai-incident-manager

    spec:
      containers:
      - name: ai-incident-manager
        image: aditya0910/ai-powered-incident-manager-app:latest

        ports:
        - containerPort: 5001

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5

        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: database-variable
              key: DB_NAME

        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: database-variable
              key: DB_USER

        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: database-variable
              key: DB_HOST

        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: database-variable
              key: DB_PORT

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PASSWORD

        - name: OLLAMA_URL
          value: http://ollama:11434

        - name: OLLAMA_MODEL
          value: tinyllama:latest

        volumeMounts:
        - name: ai-incident-storage
          mountPath: /app/data


      volumes:
      - name: ai-incident-storage
        persistentVolumeClaim:
          claimName: ai-incident-pvc
