name: Deploy to Kubernetes

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Copy Kubernetes manifests and deployment script
      - name: Copy deployment files
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "k8s,scripts/deploy.sh,scripts/verify.sh"
          target: "~/"

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

          script: |
            chmod +x ~/scripts/deploy.sh
            chmod +x ~/scripts/verify.sh

            export DB_PASSWORD='${{ secrets.DB_PASSWORD }}'
            export DOCKER_IMAGE='aditya0910/ai-powered-incident-manager-app'
            export IMAGE_TAG='${{ github.sha }}'

            ~/scripts/deploy.sh
            ~/scripts/verify.sh