name: DevSecOps End To End Pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  # CI (Continuous Integration with Security Scanning)
  Code-Quality:
    uses: ./.github/workflows/code-quality.yml

  Secrets-Scan:
    uses: ./.github/workflows/secret-scan.yml

  Dependency-Scan:
    uses: ./.github/workflows/dependency-scan.yml

  Docker-Scan:
    uses: ./.github/workflows/docker-lint.yml

  Build:
    needs: [Code-Quality, Secrets-Scan, Dependency-Scan, Docker-Scan]
    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit

  trivy:
    needs: [Build]
    uses: ./.github/workflows/image-scan.yml
    secrets: inherit

  # Deploy to production (CD)
  deploy:
    needs: [trivy]
    uses: ./.github/workflows/deploy-to-server.yml
    secrets: inherit